import type { QuestionTranslation } from "./question-types";

export const labsFrQuestionTranslations = {
  "labs_collection_date": {"prompt":"Quelle est la date de prélèvement de votre bilan sanguin le plus récent ?","why":"La date de prélèvement établit le caractère récent du bilan et évite de traiter d'anciennes valeurs comme actuelles."},
  "labs_fasting_status": {"prompt":"Étiez-vous à jeun lors du prélèvement, si le compte rendu l'indique ?","why":"Le fait d'être à jeun peut être important pour interpréter certains marqueurs et ne doit pas être supposé.","options":{"fasting":"À jeun","not_fasting":"Pas à jeun","not_stated":"Non indiqué ou incertain"}},
  "labs_reference_ranges_available": {"prompt":"Le compte rendu indique-t-il les intervalles de référence du laboratoire à côté des résultats ?","why":"L'intervalle de référence du laboratoire d'origine doit être conservé plutôt que remplacé par un seuil générique."},
  "labs_clinician_reviewed": {"prompt":"Un professionnel de santé qualifié a-t-il examiné ces résultats avec vous ?","why":"Le statut de cet examen distingue les données mesurées d'un besoin de suivi non résolu.","options":{"yes":"Oui","planned":"Un examen est prévu","no":"Non","unsure":"Je ne suis pas sûr"}},
  "lab_value_total_cholesterol": {"prompt":"Quelle valeur de cholestérol total et quelle unité figurent sur votre compte rendu récent ?","why":"La valeur et l'unité d'origine ne peuvent être utilisées que lorsqu'un modèle validé les exige."},
  "lab_value_hdl_cholesterol": {"prompt":"Quelle valeur de cholestérol HDL et quelle unité figurent sur votre compte rendu récent ?","why":"Le HDL est une donnée requise par certains modèles cardiovasculaires lorsque les critères d'admissibilité sont précisément remplis."},
  "lab_value_ldl_cholesterol": {"prompt":"Quelle valeur de cholestérol LDL et quelle unité figurent sur votre compte rendu récent ?","why":"Conserver la valeur mesurée du LDL et son unité permet un suivi lipidique transparent."},
  "lab_value_triglycerides": {"prompt":"Quelle valeur de triglycérides et quelle unité figurent sur votre compte rendu récent ?","why":"Les triglycérides dépendent du contexte de mesure, notamment du fait d'être à jeun et de l'intervalle indiqué dans le compte rendu."},
  "lab_value_hba1c": {"prompt":"Quelle valeur d'HbA1c et quelle unité figurent sur votre compte rendu récent ?","why":"L'HbA1c fournit une donnée mesurée sur la glycémie, mais n'est pas interprétée ici comme un diagnostic."},
  "lab_value_glucose": {"prompt":"Quelle valeur de glucose et quelle unité figurent sur votre compte rendu récent ?","why":"La valeur de glucose doit conserver son unité, le contexte du prélèvement et le statut à jeun pour permettre un examen sûr."},
  "lab_value_creatinine": {"prompt":"Quelle valeur de créatinine et quelle unité figurent sur votre compte rendu récent ?","why":"La créatinine ne peut fournir un contexte rénal qu'avec son unité et les facteurs personnels appropriés."},
  "lab_value_egfr": {"prompt":"Quelle valeur du DFG estimé (eGFR) figure sur votre compte rendu récent ?","why":"L'estimation fournie par le laboratoire doit être conservée sans être recalculée ni interprétée comme un diagnostic."},
  "lab_value_alt": {"prompt":"Quelle valeur d'ALT et quelle unité figurent sur votre compte rendu récent ?","why":"L'ALT n'apporte un contexte hépatique qu'avec l'intervalle d'origine et un tableau clinique plus large."},
  "lab_value_ast": {"prompt":"Quelle valeur d'AST et quelle unité figurent sur votre compte rendu récent ?","why":"L'AST n'est pas spécifique et doit rester liée au compte rendu du laboratoire et au contexte clinique."},
  "lab_value_tsh": {"prompt":"Quelle valeur de TSH et quelle unité figurent sur votre compte rendu récent ?","why":"Un résultat de TSH nécessite l'intervalle du compte rendu et le contexte clinique, plutôt qu'une classification isolée."},
  "lab_value_hemoglobin": {"prompt":"Quelle valeur d'hémoglobine et quelle unité figurent sur votre compte rendu récent ?","why":"L'hémoglobine dépend de la méthode et de la population ; le compte rendu d'origine conserve ce contexte."},
  "lab_value_ferritin": {"prompt":"Quelle valeur de ferritine et quelle unité figurent sur votre compte rendu récent ?","why":"La ferritine peut refléter plusieurs processus et ne doit pas être interprétée isolément."},
  "lab_value_vitamin_d": {"prompt":"Quelle valeur de vitamine D et quelle unité figurent sur votre compte rendu récent ?","why":"Les unités de vitamine D et les intervalles de référence varient ; les détails du compte rendu d'origine sont donc essentiels."},
} satisfies Readonly<Record<string, QuestionTranslation>>;
