import type { QuestionTranslation } from "./question-types";

export const clinicalFrQuestionTranslations = {
  "copd_breathless_frequency": {"prompt":"Au cours des quatre dernières semaines, pendant combien de temps vous êtes-vous senti essoufflé ?","why":"C'est le premier item du COPD Population Screener, un questionnaire en cinq items utilisé pour décider à qui proposer un test respiratoire (spirométrie).","options":{"none":"Jamais","little":"Rarement","some":"Une partie du temps","most":"La plupart du temps","all":"Tout le temps"}},
  "copd_phlegm": {"prompt":"Vous arrive-t-il de cracher des sécrétions, comme du mucus ou des glaires ?","why":"La production régulière de glaires est le deuxième item du COPD Population Screener.","options":{"never":"Jamais","occasional_colds":"Seulement lors de rhumes ou d'infections respiratoires occasionnels","few_days_month":"Oui, quelques jours par mois","most_days_week":"Oui, la plupart des jours de la semaine","every_day":"Oui, tous les jours"}},
  "copd_activity_limit": {"prompt":"Dans quelle mesure êtes-vous d'accord avec cette affirmation : « Je fais moins de choses qu'avant à cause de mes problèmes respiratoires » ?","why":"La limitation d'activité liée à la respiration est le troisième item du COPD Population Screener.","options":{"strongly_disagree":"Pas du tout d'accord","disagree":"Pas d'accord","unsure":"Je ne sais pas","agree":"D'accord","strongly_agree":"Tout à fait d'accord"}},
  "environment_air_pollution": {"prompt":"Votre maison est-elle régulièrement affectée par la pollution due au trafic, à la fumée ou à une mauvaise qualité de l'air extérieur ?","why":"Une exposition répétée à la pollution atmosphérique peut ajouter un contexte respiratoire et cardiovasculaire."},
  "sun_changing_mole": {"prompt":"Avez-vous remarqué un grain de beauté ou une marque cutanée qui est nouvelle, qui change, qui saigne ou qui ne guérit pas ?","why":"Une lésion cutanée changeante ou qui ne guérit pas peut justifier un examen clinique direct."},
  "sexual_contact_safety": {"prompt":"Êtes-vous inquiet de la pression, du consentement ou de la sécurité dans une situation sexuelle ?","why":"La sécurité et l'autonomie ont la priorité sur les questions courantes de santé sexuelle."},
  "pregnancy_new_concern": {"prompt":"Avez-vous un nouveau symptôme ou une aggravation qui vous préoccupe pendant la grossesse ou après l'accouchement ?","why":"Les nouvelles préoccupations pendant la grossesse ou le post-partum méritent un contexte professionnel direct."},
  "pregnancy_care_access": {"prompt":"Avez-vous actuellement accès à un professionnel des soins de maternité ou de grossesse ?","why":"L'accès aux soins influe sur les options de suivi sûres et ne doit pas être présumé."},
  "pregnancy_medication_review": {"prompt":"Un professionnel de santé qualifié a-t-il examiné vos médicaments dans ce contexte lié à la grossesse ?","why":"La grossesse peut modifier les considérations relatives aux médicaments, mais le questionnaire ne doit pas recommander de changements.","options":{"yes":"Oui","planned":"Un examen est prévu","no":"Non","unsure":"Je ne sais pas"}},
  "pregnancy_feeling_safe": {"prompt":"Vous sentez-vous en sécurité et bénéficiez-vous d'un soutien adéquat dans votre situation actuelle de grossesse ou de post-partum ?","why":"La sécurité pratique et relationnelle est un élément important du soutien pendant la grossesse et le post-partum."},
  "vision_difficulty": {"prompt":"Avez-vous des difficultés à voir, même en portant vos lunettes ou vos lentilles si vous en utilisez ?","why":"La perte de vision non traitée fait partie des facteurs de risque modifiables de démence retenus par la Commission Lancet, et elle affecte la sécurité et l'autonomie."},
  "hearing_difficulty": {"prompt":"Avez-vous des difficultés à entendre une conversation, même avec un appareil auditif si vous en utilisez un ?","why":"La perte d'audition fait partie des facteurs de risque modifiables de démence retenus par la Commission Lancet, et les appareils auditifs réduisent ce risque."},
  "blood_pressure_systolic": {"prompt":"Quel était le chiffre systolique, ou maximum, de votre lecture de tension artérielle la plus récente ?","why":"La valeur systolique mesurée est une entrée obligatoire pour certains modèles validés et pour la métrique de tension artérielle du Life's Essential 8."},
  "blood_pressure_diastolic": {"prompt": "Quel était le chiffre diastolique, ou minimum, de cette même mesure de tension artérielle ?", "why": "Le Life's Essential 8 cote la tension artérielle à partir des deux chiffres : moins de 120/80 vaut 100, et une diastolique de 80 ou plus abaisse la métrique même lorsque la systolique est normale."},
  "adolescent_pregnancy_support": {"prompt":"Souhaitez-vous des informations générales ou de l'aide pour trouver un service de santé au sujet d'une grossesse possible ou récente ?","why":"Une voie de soutien choisie par la personne évite tout calcul de grossesse et n'exige aucune information supplémentaire.","options":{"no":"Non","information":"Informations générales","service":"Aide pour trouver un service de santé"}},
  "adolescent_pregnancy_urgent_safety": {"prompt":"Avez-vous actuellement un symptôme sévère lié à la grossesse, subissez-vous des pressions ou ne vous sentez-vous pas en sécurité ?","why":"Un symptôme actuel ou un problème de sécurité nécessite une voie directe vers une aide urgente, sans poser de diagnostic."},
} satisfies Readonly<Record<string, QuestionTranslation>>;
