#!/usr/bin/env python3
"""Transcribe the printed 2019 WHO regional CVD charts into compact TypeScript.

Download the 20 two-page regional charts from
https://cdn.who.int/media/docs/default-source/cardiovascular-diseases/<region>.pdf
and the East Asia chart from
https://www.who.int/docs/default-source/ncds/19tlgh0153-appendix2.pdf.
Run: python3 scripts/generate-who-cvd-charts.py /path/to/pdf-directory
Requires pdftotext (Poppler). The input PDF names are the WHO region slugs.
The generated file is not a fitted model: each integer is a printed chart cell.
"""

import json
import re
import subprocess
import sys
from pathlib import Path

REGIONS = (
    "andean-latin-america", "australasia", "caribbean", "central-asia",
    "central-europe", "central-latin-america", "central-sub-saharan-africa",
    "east-asia", "eastern-europe", "eastern-sub-saharan-africa",
    "high-income-asia-pacific", "high-income-north-america",
    "north-africa-and-middle-east", "oceania", "south-asia", "southeast-asia",
    "southern-latin-america", "southern-sub-saharan-africa",
    "tropical-latin-america", "western-europe", "western-sub-saharan-africa",
)
AGES = ("40-44", "45-49", "50-54", "55-59", "60-64", "65-69", "70-74")
PRESSURES = ("<120", "120-139", "140-159", "160-179", "≥180")
HERE = Path(__file__).resolve().parent.parent


def page_text(pdf: Path, page: int) -> str:
    return subprocess.run(
        ["pdftotext", "-layout", "-f", str(page), "-l", str(page), str(pdf), "-"],
        check=True, capture_output=True, text=True,
    ).stdout


def chart_grids(pdf: Path, page: int, count: int) -> list[list[list[list[int]]]]:
    text = page_text(pdf, page)
    header = [line.strip() for line in text.splitlines() if line.strip()]
    assert "WHO cardiovascular disease" in header[0], (pdf, page, header[:2])
    assert re.sub(r"[^a-z0-9]+", "-", header[1].lower()).strip("-") == pdf.stem, (pdf, page, header[:2])
    rows = []
    for line in text.splitlines():
        tokens = line.split()
        if not tokens or tokens[-1] not in PRESSURES:
            continue
        charts = []
        values = []
        for token in tokens:
            if re.fullmatch(r"\d\d-\d\d", token):
                continue
            if token in PRESSURES:
                assert len(values) == 20, (pdf, page, line)
                charts.append((values, token))
                values = []
            else:
                values.append(int(token))
        assert len(charts) == count, (pdf, page, line)
        rows.append(charts)
    assert len(rows) == 35, (pdf, page, len(rows))
    labels = re.findall(r"^\s*(\d\d-\d\d)\s", text, re.M)
    assert [label for label in labels if label in AGES] == list(reversed(AGES)), (pdf, page, labels)

    grids = [[[[0] * 20 for _ in PRESSURES] for _ in AGES] for _ in range(count)]
    for row_index, row in enumerate(rows):
        age_index, pressure_index = 6 - row_index // 5, 4 - row_index % 5
        for chart_index, (values, label) in enumerate(row):
            assert label == PRESSURES[pressure_index], (pdf, page, row_index)
            assert all(0 <= value < 100 for value in values), (pdf, page, row_index)
            grids[chart_index][age_index][pressure_index] = values
    return grids


def encoded(grid: list[list[list[int]]], sex: int, smoker: int) -> str:
    start = (sex * 2 + smoker) * 5
    values = [
        value
        for age in grid
        for pressure in age
        for value in pressure[start:start + 5]
    ]
    assert len(values) == 175
    return "".join(f"{value:02d}" for value in values)


def main() -> None:
    pdf_dir = Path(sys.argv[1])
    lab, nonlab = {}, {}
    for region in REGIONS:
        pdf = pdf_dir / f"{region}.pdf"
        no_diabetes, diabetes = chart_grids(pdf, 1, 2)
        (nonlaboratory,) = chart_grids(pdf, 2, 1)
        # [sex male/female][diabetes no/yes][smoker no/yes]
        lab[region] = [
            encoded(grid, sex, smoker)
            for sex in range(2)
            for grid in (no_diabetes, diabetes)
            for smoker in range(2)
        ]
        # [sex male/female][smoker no/yes]
        nonlab[region] = [
            encoded(nonlaboratory, sex, smoker)
            for sex in range(2)
            for smoker in range(2)
        ]
    assert sum(len(value) // 2 for rows in lab.values() for value in rows) == 29_400
    assert sum(len(value) // 2 for rows in nonlab.values() for value in rows) == 14_700

    destination = HERE / "app/data/who-cvd-charts.ts"
    destination.write_text(
        '// Generated by scripts/generate-who-cvd-charts.py from WHO 2019 printed regional charts.\n'
        '// Index: [sex][diabetes][smoking][age 40–74 / 5][SBP band][cholesterol band], two digits per cell.\n'
        '// Non-laboratory charts omit diabetes and use BMI instead of cholesterol.\n'
        'import type { WhoCvdRegion } from "./countries";\n\n'
        'export const WHO_LAB_CHARTS: Readonly<Record<WhoCvdRegion, ReadonlyArray<string>>> = '
        + json.dumps(lab, indent=2, ensure_ascii=False)
        + ';\n\n'
        'export const WHO_NONLAB_CHARTS: Readonly<Record<WhoCvdRegion, ReadonlyArray<string>>> = '
        + json.dumps(nonlab, indent=2, ensure_ascii=False)
        + ';\n',
    )
    print(f"{destination}: 29,400 laboratory and 14,700 non-laboratory printed cells")


if __name__ == "__main__":
    main()
